[package]
name = "merni"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [
    "Arpad Borsos <swatinem@swatinem.de>",
]
documentation = "https://docs.rs/merni"
homepage = "https://github.com/Swatinem/merni"
repository = "https://github.com/Swatinem/merni"
description = "A low overhead metrics implementation."
autobenches = false

[features]
cadence1 = ["dep:cadence"]
iai = []

[dependencies]
cadence = { version = "1.3.0", optional = true }
crossbeam-utils = "0.8.19"
quanta = "0.12.2"
rustc-hash = "1.1.0"
smallvec = "2.0.0-alpha.5"
smol_buf = "0.1.0"
smol_str = "0.2.1"
thread_local = "1.1.8"

[dev-dependencies]
divan = "0.1.14"

[target.'cfg(unix)'.dev-dependencies]
iai-callgrind = "0.11.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
debug = 1

# DIVAN_MIN_TIME=0.25 DIVAN_THREADS=1 cargo bench
[[bench]]
name = "divan"
harness = false

[[bench]]
name = "callgrind"
harness = false
required-features = ["iai"]
