[package]
name = "merni"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [
    "Arpad Borsos <swatinem@swatinem.de>",
]
documentation = "https://docs.rs/merni"
homepage = "https://github.com/Swatinem/merni"
repository = "https://github.com/Swatinem/merni"
description = "A low overhead metrics implementation."

[features]
cadence1 = ["dep:cadence"]

[dependencies]
cadence = { version = "1.0.0", optional = true }
crossbeam-utils = "0.8.19"
quanta = "0.12.2"
smallvec = "2.0.0-alpha.5"
smol_str = "0.2.1"

[dev-dependencies]
cadence = "1.0.0"
cadence29 = { package = "cadence", version = "0.29.0" }
cadence-macros = "1.0.0"
divan = "0.1.7"
metrics = "0.21.1"
metrics-exporter-statsd = "0.6.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# DIVAN_MIN_TIME=0.25 DIVAN_THREADS=1 DIVAN_ITEMS_COUNT=1 cargo bench
[profile.bench]
debug = 1
codegen-units = 1
lto = true

[[bench]]
name = "cadence"
harness = false

[[bench]]
name = "metrics_noop"
harness = false

[[bench]]
name = "metrics_statsd"
harness = false

[[bench]]
name = "merni"
harness = false
