[package]
name = "merni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
cadence = "1.0.0"
cadence29 = { package = "cadence", version = "0.29.0" }
cadence-macros = "1.0.0"
divan = "0.1.4"
metrics = "0.21.1"
metrics-exporter-statsd = "0.6.0"

[[bench]]
name = "cadence"
harness = false

[[bench]]
name = "metrics_noop"
harness = false

[[bench]]
name = "metrics_statsd"
harness = false

[[bench]]
name = "merni"
harness = false
